labels:
  - name: blur
    overlap: true
  - name: roi1
    overlap: false

videos:
  - video_file: "video.mkv"
    label_file: "labels.json"
  - video_file: "video2.mkv"
    label_file: "labels2.json"

